### PR TITLE
Social buttons

### PR DESCRIPTION
**Pull request by thymikee**

### CODE REVIEW

**Comment by pkellner** [comment]
Also, please make sure you update the menu for register and login before end of work today

**Comment by thymikee** [comment]
Just added the login and registration

**Comment by pkellner** [comment]
Thanks.  I'm onsite at Hotel for next few hours so can't check.  I'm assuming you will do pull request.

**Comment by thymikee** [comment]
It's available in this pull request, visally just above my comment, commit a049dbd. I've put screenshots on basecamp, you can check it out there.

**Pull request merged**
